FROM python:3.9-slim

WORKDIR /app

COPY master/ ./
RUN pip install --trusted-host pypi.org --trusted-host files.pythonhosted.org  -r requirements.txt

EXPOSE 6000

CMD ["fastapi", "run", "master.py", "--port", "6000"]
